# Generated by Django 5.1 on 2024-08-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка машины')),
                ('model', models.CharField(max_length=100, verbose_name='Модель машины')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('бензин', 'Бензин'), ('дизель', 'Дизель'), ('гибрид', 'Гибрид'), ('электричество', 'Электричество')], max_length=100, verbose_name='Тип топлива')),
                ('transmission_type', models.CharField(choices=[('механическая', 'Механическая'), ('робот', 'Робот'), ('автоматическая', 'Автоматическая'), ('вариатор', 'Вариатор')], max_length=100, verbose_name='Тип коробки передач')),
                ('mieleage', models.IntegerField(verbose_name='Пробег')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
