# Generated by Django 5.1 on 2024-08-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='mieleage',
            new_name='mileage',
        ),
    ]
