# Generated by Django 5.1 on 2024-08-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_mieleage_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('disel', 'Дизель'), ('hybrid', 'Гибрид'), ('electro', 'Электричество')], max_length=100, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('mechanical', 'Механическая'), ('robot', 'Робот'), ('automatic', 'Автоматическая'), ('variator', 'Вариатор')], max_length=100, verbose_name='Тип коробки передач'),
        ),
    ]
