# Generated by Django 5.1 on 2024-08-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_fuel_type_alter_car_transmission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('disel', 'Disel'), ('hybrid', 'Hybrid'), ('electro', 'Electro')], max_length=100, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('mechanical', 'Mechanical'), ('robot', 'Robot'), ('automatic', 'Automatic'), ('variator', 'Variator')], max_length=100, verbose_name='Тип коробки передач'),
        ),
    ]
